---
- version: "2"
- plugins:
    sonar-java:
      enabled: true
      config:
        sonar.java.source: 8
    fixme:
      enabled: true
    checkstyle:
      enabled: true
    pmd:
      enabled: true